// <auto-generated>
//   WPF on Linux · Accessibility COM 互操作最小兼容层
//
//   背景：WindowsBase 的 Shared/MS/Win32/UnsafeNativeMethodsCLR.cs 引用
//   `Accessibility.IAccessible`（.NET Framework 时代随框架分发的 COM 互操作
//   程序集）。.NET (Core) 不再自带该程序集，Linux 上亦不可用。
//
//   这里只补齐「编译可见 + COM 标识正确」所需的最小面：
//     * Guid / InterfaceIsDual 与真实 MSAA IAccessible 一致 —— 这两项决定了
//       COM 封送时能否正确建立 RCW，是本文件唯一对封送有影响的部分；
//     * 成员表留空，因为上游仅在 `ObjectFromLresult(..., ref IAccessible ppvObject)`
//       的 extern 声明中把它当作不透明句柄使用，不调用任何方法。
//   注意：在真正调用任何 MSAA 方法之前，必须按 MSAA IDL 补齐成员表与 [DispId]，
//   否则拿到的 RCW 无法做方法调用。
// </auto-generated>

namespace Accessibility
{
    /// <summary>MSAA IAccessible 的空壳声明，仅用于编译期类型可见。</summary>
    [System.Runtime.InteropServices.ComImport]
    [System.Runtime.InteropServices.Guid("618736E0-3C3D-11CF-810C-00AA00389B71")]
    [System.Runtime.InteropServices.InterfaceType(
        System.Runtime.InteropServices.ComInterfaceType.InterfaceIsDual)]
    internal interface IAccessible
    {
    }
}
