/* generated by gen_proxy.py - do not edit */
	.text
	.globl GetNextPerfElementId
	.p2align 4
GetNextPerfElementId:
	jmp *ptr_GetNextPerfElementId(%rip)
	.globl IWICColorContext_GetExifColorSpace_Proxy
	.p2align 4
IWICColorContext_GetExifColorSpace_Proxy:
	jmp *ptr_IWICColorContext_GetExifColorSpace_Proxy(%rip)
	.globl IWICColorContext_GetProfileBytes_Proxy
	.p2align 4
IWICColorContext_GetProfileBytes_Proxy:
	jmp *ptr_IWICColorContext_GetProfileBytes_Proxy(%rip)
	.globl IWICColorContext_GetType_Proxy
	.p2align 4
IWICColorContext_GetType_Proxy:
	jmp *ptr_IWICColorContext_GetType_Proxy(%rip)
	.globl InteropDeviceBitmap_AddDirtyRect
	.p2align 4
InteropDeviceBitmap_AddDirtyRect:
	jmp *ptr_InteropDeviceBitmap_AddDirtyRect(%rip)
	.globl InteropDeviceBitmap_Create
	.p2align 4
InteropDeviceBitmap_Create:
	jmp *ptr_InteropDeviceBitmap_Create(%rip)
	.globl InteropDeviceBitmap_Detach
	.p2align 4
InteropDeviceBitmap_Detach:
	jmp *ptr_InteropDeviceBitmap_Detach(%rip)
	.globl InteropDeviceBitmap_GetAsSoftwareBitmap
	.p2align 4
InteropDeviceBitmap_GetAsSoftwareBitmap:
	jmp *ptr_InteropDeviceBitmap_GetAsSoftwareBitmap(%rip)
	.globl MIL3DCalcProjected2DBounds
	.p2align 4
MIL3DCalcProjected2DBounds:
	jmp *ptr_MIL3DCalcProjected2DBounds(%rip)
	.globl MILAddRef
	.p2align 4
MILAddRef:
	jmp *ptr_MILAddRef(%rip)
	.globl MILCreateEventProxy
	.p2align 4
MILCreateEventProxy:
	jmp *ptr_MILCreateEventProxy(%rip)
	.globl MILCreateFactory
	.p2align 4
MILCreateFactory:
	jmp *ptr_MILCreateFactory(%rip)
	.globl MILCreateStreamFromStreamDescriptor
	.p2align 4
MILCreateStreamFromStreamDescriptor:
	jmp *ptr_MILCreateStreamFromStreamDescriptor(%rip)
	.globl MILFactoryCreateBitmapRenderTarget
	.p2align 4
MILFactoryCreateBitmapRenderTarget:
	jmp *ptr_MILFactoryCreateBitmapRenderTarget(%rip)
	.globl MILFactoryCreateMediaPlayer
	.p2align 4
MILFactoryCreateMediaPlayer:
	jmp *ptr_MILFactoryCreateMediaPlayer(%rip)
	.globl MILFactoryCreateSWRenderTargetForBitmap
	.p2align 4
MILFactoryCreateSWRenderTargetForBitmap:
	jmp *ptr_MILFactoryCreateSWRenderTargetForBitmap(%rip)
	.globl MILIStreamWrite
	.p2align 4
MILIStreamWrite:
	jmp *ptr_MILIStreamWrite(%rip)
	.globl MILLoadResource
	.p2align 4
MILLoadResource:
	jmp *ptr_MILLoadResource(%rip)
	.globl MILMediaCanPause
	.p2align 4
MILMediaCanPause:
	jmp *ptr_MILMediaCanPause(%rip)
	.globl MILMediaClose
	.p2align 4
MILMediaClose:
	jmp *ptr_MILMediaClose(%rip)
	.globl MILMediaGetBufferingProgress
	.p2align 4
MILMediaGetBufferingProgress:
	jmp *ptr_MILMediaGetBufferingProgress(%rip)
	.globl MILMediaGetDownloadProgress
	.p2align 4
MILMediaGetDownloadProgress:
	jmp *ptr_MILMediaGetDownloadProgress(%rip)
	.globl MILMediaGetMediaLength
	.p2align 4
MILMediaGetMediaLength:
	jmp *ptr_MILMediaGetMediaLength(%rip)
	.globl MILMediaGetNaturalHeight
	.p2align 4
MILMediaGetNaturalHeight:
	jmp *ptr_MILMediaGetNaturalHeight(%rip)
	.globl MILMediaGetNaturalWidth
	.p2align 4
MILMediaGetNaturalWidth:
	jmp *ptr_MILMediaGetNaturalWidth(%rip)
	.globl MILMediaGetPosition
	.p2align 4
MILMediaGetPosition:
	jmp *ptr_MILMediaGetPosition(%rip)
	.globl MILMediaHasAudio
	.p2align 4
MILMediaHasAudio:
	jmp *ptr_MILMediaHasAudio(%rip)
	.globl MILMediaHasVideo
	.p2align 4
MILMediaHasVideo:
	jmp *ptr_MILMediaHasVideo(%rip)
	.globl MILMediaIsBuffering
	.p2align 4
MILMediaIsBuffering:
	jmp *ptr_MILMediaIsBuffering(%rip)
	.globl MILMediaNeedUIFrameUpdate
	.p2align 4
MILMediaNeedUIFrameUpdate:
	jmp *ptr_MILMediaNeedUIFrameUpdate(%rip)
	.globl MILMediaOpen
	.p2align 4
MILMediaOpen:
	jmp *ptr_MILMediaOpen(%rip)
	.globl MILMediaProcessExitHandler
	.p2align 4
MILMediaProcessExitHandler:
	jmp *ptr_MILMediaProcessExitHandler(%rip)
	.globl MILMediaSetBalance
	.p2align 4
MILMediaSetBalance:
	jmp *ptr_MILMediaSetBalance(%rip)
	.globl MILMediaSetIsScrubbingEnabled
	.p2align 4
MILMediaSetIsScrubbingEnabled:
	jmp *ptr_MILMediaSetIsScrubbingEnabled(%rip)
	.globl MILMediaSetPosition
	.p2align 4
MILMediaSetPosition:
	jmp *ptr_MILMediaSetPosition(%rip)
	.globl MILMediaSetRate
	.p2align 4
MILMediaSetRate:
	jmp *ptr_MILMediaSetRate(%rip)
	.globl MILMediaSetVolume
	.p2align 4
MILMediaSetVolume:
	jmp *ptr_MILMediaSetVolume(%rip)
	.globl MILMediaShutdown
	.p2align 4
MILMediaShutdown:
	jmp *ptr_MILMediaShutdown(%rip)
	.globl MILMediaStop
	.p2align 4
MILMediaStop:
	jmp *ptr_MILMediaStop(%rip)
	.globl MILQueryInterface
	.p2align 4
MILQueryInterface:
	jmp *ptr_MILQueryInterface(%rip)
	.globl MILRelease
	.p2align 4
MILRelease:
	jmp *ptr_MILRelease(%rip)
	.globl MILRenderTargetBitmapClear
	.p2align 4
MILRenderTargetBitmapClear:
	jmp *ptr_MILRenderTargetBitmapClear(%rip)
	.globl MILRenderTargetBitmapGetBitmap
	.p2align 4
MILRenderTargetBitmapGetBitmap:
	jmp *ptr_MILRenderTargetBitmapGetBitmap(%rip)
	.globl MILSwDoubleBufferedBitmapAddDirtyRect
	.p2align 4
MILSwDoubleBufferedBitmapAddDirtyRect:
	jmp *ptr_MILSwDoubleBufferedBitmapAddDirtyRect(%rip)
	.globl MILSwDoubleBufferedBitmapCreate
	.p2align 4
MILSwDoubleBufferedBitmapCreate:
	jmp *ptr_MILSwDoubleBufferedBitmapCreate(%rip)
	.globl MILSwDoubleBufferedBitmapGetBackBuffer
	.p2align 4
MILSwDoubleBufferedBitmapGetBackBuffer:
	jmp *ptr_MILSwDoubleBufferedBitmapGetBackBuffer(%rip)
	.globl MILSwDoubleBufferedBitmapProtectBackBuffer
	.p2align 4
MILSwDoubleBufferedBitmapProtectBackBuffer:
	jmp *ptr_MILSwDoubleBufferedBitmapProtectBackBuffer(%rip)
	.globl MILUpdateSystemParametersInfo
	.p2align 4
MILUpdateSystemParametersInfo:
	jmp *ptr_MILUpdateSystemParametersInfo(%rip)
	.globl MilChannel_CloseBatch
	.p2align 4
MilChannel_CloseBatch:
	jmp *ptr_MilChannel_CloseBatch(%rip)
	.globl MilChannel_GetMarshalType
	.p2align 4
MilChannel_GetMarshalType:
	jmp *ptr_MilChannel_GetMarshalType(%rip)
	.globl MilChannel_SetNotificationWindow
	.p2align 4
MilChannel_SetNotificationWindow:
	jmp *ptr_MilChannel_SetNotificationWindow(%rip)
	.globl MilChannel_SetReceiveBroadcastMessages
	.p2align 4
MilChannel_SetReceiveBroadcastMessages:
	jmp *ptr_MilChannel_SetReceiveBroadcastMessages(%rip)
	.globl MilCompositionEngine_DeinitializePartitionManager
	.p2align 4
MilCompositionEngine_DeinitializePartitionManager:
	jmp *ptr_MilCompositionEngine_DeinitializePartitionManager(%rip)
	.globl MilCompositionEngine_EnterCompositionEngineLock
	.p2align 4
MilCompositionEngine_EnterCompositionEngineLock:
	jmp *ptr_MilCompositionEngine_EnterCompositionEngineLock(%rip)
	.globl MilCompositionEngine_ExitCompositionEngineLock
	.p2align 4
MilCompositionEngine_ExitCompositionEngineLock:
	jmp *ptr_MilCompositionEngine_ExitCompositionEngineLock(%rip)
	.globl MilCompositionEngine_GetComposedEventId
	.p2align 4
MilCompositionEngine_GetComposedEventId:
	jmp *ptr_MilCompositionEngine_GetComposedEventId(%rip)
	.globl MilCompositionEngine_InitializePartitionManager
	.p2align 4
MilCompositionEngine_InitializePartitionManager:
	jmp *ptr_MilCompositionEngine_InitializePartitionManager(%rip)
	.globl MilCompositionEngine_UpdateSchedulerSettings
	.p2align 4
MilCompositionEngine_UpdateSchedulerSettings:
	jmp *ptr_MilCompositionEngine_UpdateSchedulerSettings(%rip)
	.globl MilComposition_PeekNextMessage
	.p2align 4
MilComposition_PeekNextMessage:
	jmp *ptr_MilComposition_PeekNextMessage(%rip)
	.globl MilComposition_SyncFlush
	.p2align 4
MilComposition_SyncFlush:
	jmp *ptr_MilComposition_SyncFlush(%rip)
	.globl MilComposition_WaitForNextMessage
	.p2align 4
MilComposition_WaitForNextMessage:
	jmp *ptr_MilComposition_WaitForNextMessage(%rip)
	.globl MilConnection_CreateChannel
	.p2align 4
MilConnection_CreateChannel:
	jmp *ptr_MilConnection_CreateChannel(%rip)
	.globl MilConnection_DestroyChannel
	.p2align 4
MilConnection_DestroyChannel:
	jmp *ptr_MilConnection_DestroyChannel(%rip)
	.globl MilContent_AttachToHwnd
	.p2align 4
MilContent_AttachToHwnd:
	jmp *ptr_MilContent_AttachToHwnd(%rip)
	.globl MilContent_DetachFromHwnd
	.p2align 4
MilContent_DetachFromHwnd:
	jmp *ptr_MilContent_DetachFromHwnd(%rip)
	.globl MilGlyphRun_GetGlyphOutline
	.p2align 4
MilGlyphRun_GetGlyphOutline:
	jmp *ptr_MilGlyphRun_GetGlyphOutline(%rip)
	.globl MilGlyphRun_ReleasePathGeometryData
	.p2align 4
MilGlyphRun_ReleasePathGeometryData:
	jmp *ptr_MilGlyphRun_ReleasePathGeometryData(%rip)
	.globl MilPlayer_Create
	.p2align 4
MilPlayer_Create:
	jmp *ptr_MilPlayer_Create(%rip)
	.globl MilPlayer_Process
	.p2align 4
MilPlayer_Process:
	jmp *ptr_MilPlayer_Process(%rip)
	.globl MilResource_CreateCWICWrapperBitmap
	.p2align 4
MilResource_CreateCWICWrapperBitmap:
	jmp *ptr_MilResource_CreateCWICWrapperBitmap(%rip)
	.globl MilResource_DuplicateHandle
	.p2align 4
MilResource_DuplicateHandle:
	jmp *ptr_MilResource_DuplicateHandle(%rip)
	.globl MilResource_GetRefCountOnChannel
	.p2align 4
MilResource_GetRefCountOnChannel:
	jmp *ptr_MilResource_GetRefCountOnChannel(%rip)
	.globl MilResource_SendCommandBitmapSource
	.p2align 4
MilResource_SendCommandBitmapSource:
	jmp *ptr_MilResource_SendCommandBitmapSource(%rip)
	.globl MilResource_SendCommandMedia
	.p2align 4
MilResource_SendCommandMedia:
	jmp *ptr_MilResource_SendCommandMedia(%rip)
	.globl MilUtility_ArcToBezier
	.p2align 4
MilUtility_ArcToBezier:
	jmp *ptr_MilUtility_ArcToBezier(%rip)
	.globl MilUtility_CopyPixelBuffer
	.p2align 4
MilUtility_CopyPixelBuffer:
	jmp *ptr_MilUtility_CopyPixelBuffer(%rip)
	.globl MilUtility_GeometryGetArea
	.p2align 4
MilUtility_GeometryGetArea:
	jmp *ptr_MilUtility_GeometryGetArea(%rip)
	.globl MilUtility_GetPointAtLengthFraction
	.p2align 4
MilUtility_GetPointAtLengthFraction:
	jmp *ptr_MilUtility_GetPointAtLengthFraction(%rip)
	.globl MilUtility_GetTileBrushMapping
	.p2align 4
MilUtility_GetTileBrushMapping:
	jmp *ptr_MilUtility_GetTileBrushMapping(%rip)
	.globl MilUtility_PathGeometryBounds
	.p2align 4
MilUtility_PathGeometryBounds:
	jmp *ptr_MilUtility_PathGeometryBounds(%rip)
	.globl MilUtility_PathGeometryCombine
	.p2align 4
MilUtility_PathGeometryCombine:
	jmp *ptr_MilUtility_PathGeometryCombine(%rip)
	.globl MilUtility_PathGeometryFlatten
	.p2align 4
MilUtility_PathGeometryFlatten:
	jmp *ptr_MilUtility_PathGeometryFlatten(%rip)
	.globl MilUtility_PathGeometryHitTest
	.p2align 4
MilUtility_PathGeometryHitTest:
	jmp *ptr_MilUtility_PathGeometryHitTest(%rip)
	.globl MilUtility_PathGeometryHitTestPathGeometry
	.p2align 4
MilUtility_PathGeometryHitTestPathGeometry:
	jmp *ptr_MilUtility_PathGeometryHitTestPathGeometry(%rip)
	.globl MilUtility_PathGeometryOutline
	.p2align 4
MilUtility_PathGeometryOutline:
	jmp *ptr_MilUtility_PathGeometryOutline(%rip)
	.globl MilUtility_PathGeometryWiden
	.p2align 4
MilUtility_PathGeometryWiden:
	jmp *ptr_MilUtility_PathGeometryWiden(%rip)
	.globl MilUtility_PolygonBounds
	.p2align 4
MilUtility_PolygonBounds:
	jmp *ptr_MilUtility_PolygonBounds(%rip)
	.globl MilUtility_PolygonHitTest
	.p2align 4
MilUtility_PolygonHitTest:
	jmp *ptr_MilUtility_PolygonHitTest(%rip)
	.globl MilVersionCheck
	.p2align 4
MilVersionCheck:
	jmp *ptr_MilVersionCheck(%rip)
	.globl MilVisualTarget_AttachToHwnd
	.p2align 4
MilVisualTarget_AttachToHwnd:
	jmp *ptr_MilVisualTarget_AttachToHwnd(%rip)
	.globl MilVisualTarget_DetachFromHwnd
	.p2align 4
MilVisualTarget_DetachFromHwnd:
	jmp *ptr_MilVisualTarget_DetachFromHwnd(%rip)
	.globl RenderOptions_EnableHardwareAccelerationInRdp
	.p2align 4
RenderOptions_EnableHardwareAccelerationInRdp:
	jmp *ptr_RenderOptions_EnableHardwareAccelerationInRdp(%rip)
	.globl RenderOptions_ForceSoftwareRenderingModeForProcess
	.p2align 4
RenderOptions_ForceSoftwareRenderingModeForProcess:
	jmp *ptr_RenderOptions_ForceSoftwareRenderingModeForProcess(%rip)
	.globl RenderOptions_IsSoftwareRenderingForcedForProcess
	.p2align 4
RenderOptions_IsSoftwareRenderingForcedForProcess:
	jmp *ptr_RenderOptions_IsSoftwareRenderingForcedForProcess(%rip)
	.globl SetMilPerfInstrumentationFlags
	.p2align 4
SetMilPerfInstrumentationFlags:
	jmp *ptr_SetMilPerfInstrumentationFlags(%rip)
	.globl WgxConnection_Create
	.p2align 4
WgxConnection_Create:
	jmp *ptr_WgxConnection_Create(%rip)
	.globl WgxConnection_Disconnect
	.p2align 4
WgxConnection_Disconnect:
	jmp *ptr_WgxConnection_Disconnect(%rip)
	.globl WgxConnection_SameThreadPresent
	.p2align 4
WgxConnection_SameThreadPresent:
	jmp *ptr_WgxConnection_SameThreadPresent(%rip)
	.globl WgxConnection_ShouldForceSoftwareForGraphicsStreamClient
	.p2align 4
WgxConnection_ShouldForceSoftwareForGraphicsStreamClient:
	jmp *ptr_WgxConnection_ShouldForceSoftwareForGraphicsStreamClient(%rip)
