#!/usr/bin/env python3
"""Generate the app-local wpfgfx_cor3.dll forwarding proxy sources from an export list.

  python gen_proxy.py exports.json outdir

Emits:
  proxy_exports.h  - the U1_EXPORTS(X) macro list
  stubs.s          - `jmp *ptr_NAME(%rip)` trampolines for every export we do not intercept
  proxy.def        - reference .def (kept for documentation / manual linking)
"""
import json
import os
import sys

# exports that are intercepted in C (proxy.c) and therefore must not get an asm stub
INTERCEPTED = [
    "MilChannel_BeginCommand",
    "MilChannel_AppendCommandData",
    "MilChannel_EndCommand",
    "MilChannel_CommitChannel",
    "MilResource_SendCommand",
    "MilResource_CreateOrAddRefOnChannel",
    "MilResource_ReleaseOnChannel",
]


def main():
    exports_json, outdir = sys.argv[1], sys.argv[2]
    info = json.load(open(exports_json, encoding="utf-8"))
    ex = info["exports"]
    names = [e["name"] for e in ex]
    stubbed = [n for n in names if n not in INTERCEPTED]
    missing = [n for n in INTERCEPTED if n not in names]
    noncode = [e["name"] for e in ex if e["kind"] != "code"]

    os.makedirs(outdir, exist_ok=True)

    rows = " \\\n".join(f"    X({n})" for n in sorted(names))
    with open(os.path.join(outdir, "proxy_exports.h"), "w", encoding="utf-8") as f:
        f.write("/* generated by gen_proxy.py - do not edit */\n")
        f.write("/* source: %s (%d named exports) */\n" % (info["path"], len(names)))
        f.write("#ifndef U1_PROXY_EXPORTS_H\n#define U1_PROXY_EXPORTS_H\n\n")
        f.write("#define U1_EXPORTS(X) \\\n%s\n\n" % rows)
        f.write("#define U1_INTERCEPTED(X) \\\n%s\n\n" % " \\\n".join(f"    X({n})" for n in INTERCEPTED))
        f.write("#endif\n")

    with open(os.path.join(outdir, "stubs.s"), "w", encoding="utf-8") as f:
        f.write("/* generated by gen_proxy.py - do not edit */\n")
        f.write("\t.text\n")
        for n in sorted(stubbed):
            f.write("\t.globl %s\n\t.p2align 4\n%s:\n\tjmp *ptr_%s(%%rip)\n" % (n, n, n))

    with open(os.path.join(outdir, "proxy.def"), "w", encoding="utf-8") as f:
        f.write("; generated by gen_proxy.py - reference only\nLIBRARY wpfgfx_cor3\nEXPORTS\n")
        for n in sorted(names):
            f.write("    %s\n" % n)

    print("named exports      : %d" % len(names))
    print("intercepted in C   : %d (%s)" % (len(INTERCEPTED), ", ".join(INTERCEPTED)))
    print("asm trampolines    : %d" % len(stubbed))
    if missing:
        print("!! intercepted names NOT present in the real DLL: %s" % ", ".join(missing))
    if noncode:
        print("!! non-code exports (cannot be jmp-stubbed): %s" % ", ".join(noncode))


if __name__ == "__main__":
    main()
